### ISSUE TITLE
Can't push to repo

### ISSUE THREAD

**Issue by vvicho** [9001-Solutions/ffxivclock-data#7]
Not sure if it's my configuration or the repo's but in August 13th GitHub auth changed to no longer accept passwords and now use 2FA or some other things.. 

Found this post showing how to fix the issue
https://reactgo.com/github-password-authentication-removed/

**Comment by CodyRWhite** [comment]
I am a bit confused by the "issue". 

I do not see any prior commits from your user account. Did you have direct access to the repository? If so you will need to create an access token to authenticate to the repo's now. 

This is not something with the repository, this is an access token that you create for your user account.

**Comment by vvicho** [comment]
maybe I'm just missing access to the repo. already created the token but still getting denied when pushing

**Comment by CodyRWhite** [comment]
If you want to make changes to the repo. Do the following.

Make a fork
Update your changes
Create a pull request for your changes. 

If the members of the repo approve you changes they will merge your pull request into master/main.

**Comment by 9001-Sols** [comment]
You won't be able to push directly to this repo, but if you fork it and create a Pull Request, I can approve and merge your changes.
